name: 'Julia compute test matrix'
description: 'Compute a test matrix'
inputs:
  include-release-versions:
    type: boolean
    required: false
    default: true
  include-lts-versions:
    type: boolean
    required: false
    default: true
  include-all-compatible-minor-versions:
    type: boolean
    required: false
    default: false
  include-smallest-compatible-minor-versions:
    type: boolean
    required: false
    default: true
  include-rc-versions:
    type: boolean
    required: false
    default: false
  include-beta-versions:
    type: boolean
    required: false
    default: false
  include-alpha-versions:
    type: boolean
    required: false
    default: false
  include-nightly-versions:
    type: boolean
    required: false
    default: false
  include-windows-x64:
    type: boolean
    required: false
    default: true
  include-windows-x86:
    type: boolean
    required: false
    default: true
  include-linux-x64:
    type: boolean
    required: false
    default: true
  include-linux-x86:
    type: boolean
    required: false
    default: true
  include-macos-x64:
    type: boolean
    required: false
    default: true
  include-macos-aarch64:
    type: boolean
    required: false
    default: true
outputs:
  test-matrix:
    description: 'The computed test matrix'
runs:
  using: 'node20'
  main: 'dist/index.js'
