name: 'Julia Juliaup Channel Computation'
description: 'Compute compatible Juliaup channels'
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: project-hash
      with:
        script: |
          const crypto = require('crypto')
          const path = require('path')
          const fs = require('fs')
          console.log('THe orig is')
          console.log(process.env.GITHUB_ACTION_PATH)
          const ourPath = path.join(process.env.GITHUB_ACTION_PATH, 'Manifest.toml')
          console.log('Our path is')
          console.log(ourPath)

          const filecontent = fs.readdirSync(ourPath)

          console.log('The directory content is')
          console.log(filecontent)

          console.log('The file exists')
          console.log(fs.existsSync(OurPath))

          const ourHash = crypto.createHash('sha1').setEncoding('hex')

          const ourResult = fs.createReadStream(ourPath).pipe(ourHash, 'finish').digest('hex')

          console.log('Our result is')
          console.log(ourResult)

          return ourResult
        result-encoding: string
    - name: Check Julia version
      shell: bash
      id: julia-version
      run: |
        echo "juliaversion=$(julia -v)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: cache-project
      with:
        path: ${{ github.action_path }}/.julia
        key: julia-get-compatible-juliaup-channels-cache-${{ runner.os }}-${{ steps.julia-version.outputs.juliaversion }}-${{ steps.project-hash.outputs.result }}
    - name: Install and precompile
      if: steps.cache-project.outputs.cache-hit != 'true'
      run: julia --project=${{ github.action_path }} -e 'import Pkg; Pkg.instantiate()'
      shell: bash
      env:
        JULIA_DEPOT_PATH: ${{ github.action_path }}/.julia
    - uses: actions/cache/save@v3
      if: steps.cache-project.outputs.cache-hit != 'true'
      with:
        path: ${{ github.action_path }}/.julia
        key: julia-get-compatible-juliaup-channels-cache-${{ runner.os }}-${{ steps.julia-version.outputs.juliaversion }}-${{ steps.project-hash.outputs.result }}
    - name: Compute compabitle Juliaup channels
      run: julia --project=${{ github.action_path }} ${{ github.action_path }}/main.jl
      shell: bash
      env:
        JULIA_DEPOT_PATH: ${{ github.action_path }}/.julia
